CREATE DATABASE IF NOT EXISTS DETRAN;

USE DETRAN;

CREATE TABLE VEICULO(
    PLACA CHAR(8) PRIMARY KEY NOT NULL UNIQUE,
    MARCA VARCHAR(20) NOT NULL,
    MODELO VARCHAR(20) NOT NULL,
    COR VARCHAR(20) NOT NULL,
    ANO INT NOT NULL,
    CPF_MOTORISTA CHAR(11) NOT NULL
);

CREATE TABLE MULTA (
    IDMULTA INT PRIMARY KEY AUTO_INCREMENT,
    VALOR FLOAT(7,2) NOT NULL,
    DATA DATE NOT NULL,
    PONTOS INT(2) NOT NULL,
    TIPO VARCHAR(40) NOT NULL,
    PLACA_CARRO CHAR(8) NOT NULL
);

CREATE TABLE MOTORISTA(
    CPF CHAR(11) PRIMARY KEY NOT NULL UNIQUE,
    NOME VARCHAR(100) NOT NULL,
    VENCIMENTO_CNH DATE NOT NULL,
    CATEGORIA_CNH ENUM('A','B','AB') NOT NULL
);

ALTER TABLE MULTA
ADD CONSTRAINT FK_MULTA_VEICULOPLACA
FOREIGN KEY (PLACA_CARRO)
REFERENCES VEICULO(PLACA);

ALTER TABLE VEICULO
ADD CONSTRAINT FK_VEICULO_MOTORISTACPF
FOREIGN KEY (CPF_MOTORISTA)
REFERENCES MOTORISTA(CPF);